name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (major/minor/patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Import GPG Key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Configure Git
        run: |
          git config --global user.email "${{ steps.import-gpg.outputs.email }}"
          git config --global user.name "${{ steps.import-gpg.outputs.name }}"
          git config --global commit.gpgsign true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Determine New Version
        id: new_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          NEW_VERSION=$(npm version ${{ github.event.inputs.release-type }} --no-git-tag-version)
          NEW_VERSION_CLEAN=${NEW_VERSION#v}
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "new_version=$NEW_VERSION_CLEAN" >> $GITHUB_ENV

      - name: Create or Checkout Release Branch
        run: |
          BRANCH="release/v${{ env.new_version }}"
          if git show-ref --quiet refs/heads/$BRANCH; then
            git checkout $BRANCH
          else
            git checkout -b $BRANCH
          fi

      - name: Update Dependencies and Version
        run: |
          npm install
          git add package.json package-lock.json
          git commit -m "chore: bump version to ${{ env.new_version }}" || echo "No changes to commit"

      - name: Push Changes
        run: |
          BRANCH="release/v${{ env.new_version }}"
          git push origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump version to ${{ env.new_version }}"
          branch: "release/v${{ env.new_version }}"
          base: main
          title: "Release v${{ env.new_version }}"
          body: "Automated release PR for version ${{ env.new_version }}"
          delete-branch: false
          draft: false
          labels: 'release, automated'
          reviewers: 'EvanNotFound'
          assignees: 'EvanNotFound'

      - name: Create GitHub Release (Draft)
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ env.new_version }}"
          name: "v${{ env.new_version }}"
          body: "Release v${{ env.new_version }}"
          draft: true
          prerelease: false