name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (major/minor/patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          
      - name: Configure Git
        run: |
          git config --global user.email "${{ steps.import-gpg.outputs.email }}"
          git config --global user.name "${{ steps.import-gpg.outputs.name }}"
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create Release Branch and Update Version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          BRANCH="release/v${VERSION}"
          git checkout -b $BRANCH || git checkout $BRANCH
          npm run release:${{ github.event.inputs.release-type }}
          
      - name: Update package-lock.json
        run: npm install
        
      - name: Commit Changes
        run: |
          NEW_VERSION=$(node -p "require('./package.json').version")
          if ! git diff --quiet; then
            git add package.json package-lock.json
            git commit -m "chore: bump version to ${NEW_VERSION}"
            git push -u origin $BRANCH
          else
            echo "No changes to commit"
            exit 1
          fi
          
      - name: Create Pull Request
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEW_VERSION=$(node -p "require('./package.json').version")
          gh pr create --base main --head "release/v${NEW_VERSION}" --title "Release v${NEW_VERSION}" --body "Automated release PR for version ${NEW_VERSION}" || echo "PR already exists"

      - name: Create GitHub Release (Draft)
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEW_VERSION=$(node -p "require('./package.json').version")
          gh release create "v${NEW_VERSION}" \
            --draft \
            --title "v${NEW_VERSION}" \
            --notes "Release v${NEW_VERSION}" || echo "Release already exists"